version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo npm install -g gatsby-cli
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: git config --global user.email "circleci@noop.com"
      - run: git config --global user.name "CI"
      - run: npm run build
      - run: echo fagsamling.vismaconsulting.no > public/CNAME
      - run: cp -rv .circleci public/
      - run: npm run deploy
